# Generated by Django 4.1.1 on 2022-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Stuff'), (1, 'Teacher'), (2, 'Student')], default=2),
        ),
    ]
